# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160512_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
